- name: "Build hosts file"
  template: src=hosts.j2 dest=/etc/hosts mode=0644 owner=root group=root backup=yes

- name: "Install packages"
  yum: name={{ item }} state=installed
  with_items: 
    - ${install_packages} # sourced from vars/RedHat.yml
  when: ansible_pkg_mgr == 'yum'

- name: "Install packages"
  apt: pkg={{ item }} state=installed
  with_items:
    - ${install_packages} # sourced from vars/Debian.yml
  when: ansible_pkg_mgr == 'apt'

- name: "Copy rsyslog config"
  template: src=rsyslog.conf.j2 dest={{ syslog_conf_path }}{{ syslog_conf_file }} owner=root group=root mode=0644 backup=yes
  notify: Restart rsyslog
